dataset_path: ../data
model_size: small
checkpoint_dir: ../training/checkpoints/waste_cls_jitter_vf_small
checkpoint_name: waste_cls_jitter_vf_small
exp_name: waste_cls_jitter_vf_small
version: 1
log_dir: '../training/logs/'
metrics_dir: '../training/metrics/'
verbose: True
num_workers: 15
lr: 0.0001
epochs: 50
batch_size: 64
patience: 5
horizontal_flip: 0.5
vertical_flip: 0.5
rotation: 20
brightness: 0.2
contrast: 0.2
saturation: 0.1
hue: 0